#!/bin/bash --

# This is a list of git clone / build statements
# ToDo: can this be more elegant?

# Ensure we have a projects folder for source and builds
cd~
mkdir -p ~/projects # Uses -p to prevent error when folder already exists
cd ~/projects

# VSCode
git clone https://aur.archlinux.org/visual-studio-code-bin.git
cd visual-studio-code-bin/
makepkg -si
cd ..

# evdi
git clone https://aur.archlinux.org/evdi.git
cd evdi/
makepkg -si
cd ..

# DisplayLink drivers
git clone https://aur.archlinux.org/displaylink.git
cd displaylink/
makepkg -si
cd ..

sudo systemctl enable displaylink
sudo systemctl start displaylink
