#!/bin/bash --

echo -e "\nInstalling packages from pacman, please"
echo -e "supply the user password when prompted,"
echo -e "and the wifi password for 2400 when asked\n"

sudo pacman -S --noconfirm --needed \
    tldr \
    go \
    fzf \
    bat \
    firefox \
    tmux \
    git \
    fd \
    yazi \
    eza \
    unzip \
    networkmanager \
    remmina \
    freerdp \
    linux-headers \
    pass \
    less \
    stow \
    sane-airscan \
    poppler \
    qpdf \
    glow \
    jq \
    wl-clipboard \
    cups \
    libreoffice-still

sudo systemctl enable NetworkManager
sudo systemctl start NetworkManager

# Let's try to wait for service startup before connecting
sleep 5

nmcli device wifi connect 2400 --ask

echo -e "\npacman install complete, and wifi up."
echo -e "Control the wifi radio as follows:\n"
echo -e "nmcli radio wifi off|on\n"

lpadmin -p LexmarkPrt -D "Lexmark CX310dn" -E -v socket://lexmarkprt.loc
